//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1008.
// 
#pragma warning disable 1591

namespace Escc.Cms.ResourceHelper.CmsResourcesProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ResourcesProxySoap", Namespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices")]
    public partial class ResourcesProxy : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RootResourceGalleryProxyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResourceGalleryProxyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ResourcesProxy() {
            this.Url = global::Escc.Cms.ResourceHelper.Properties.Settings.Default.Escc_Cms_ResourceHelper_CmsResourcesProxy_ResourcesProxy;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RootResourceGalleryProxyCompletedEventHandler RootResourceGalleryProxyCompleted;
        
        /// <remarks/>
        public event ResourceGalleryProxyCompletedEventHandler ResourceGalleryProxyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/Escc.Cms.WebServices/RootResourceGalleryProxy", RequestNamespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices", ResponseNamespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CmsResourceGallery RootResourceGalleryProxy() {
            object[] results = this.Invoke("RootResourceGalleryProxy", new object[0]);
            return ((CmsResourceGallery)(results[0]));
        }
        
        /// <remarks/>
        public void RootResourceGalleryProxyAsync() {
            this.RootResourceGalleryProxyAsync(null);
        }
        
        /// <remarks/>
        public void RootResourceGalleryProxyAsync(object userState) {
            if ((this.RootResourceGalleryProxyOperationCompleted == null)) {
                this.RootResourceGalleryProxyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRootResourceGalleryProxyOperationCompleted);
            }
            this.InvokeAsync("RootResourceGalleryProxy", new object[0], this.RootResourceGalleryProxyOperationCompleted, userState);
        }
        
        private void OnRootResourceGalleryProxyOperationCompleted(object arg) {
            if ((this.RootResourceGalleryProxyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RootResourceGalleryProxyCompleted(this, new RootResourceGalleryProxyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.eastsussex.gov.uk/Escc.Cms.WebServices/ResourceGalleryProxy", RequestNamespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices", ResponseNamespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CmsResourceGallery ResourceGalleryProxy(System.Guid guid) {
            object[] results = this.Invoke("ResourceGalleryProxy", new object[] {
                        guid});
            return ((CmsResourceGallery)(results[0]));
        }
        
        /// <remarks/>
        public void ResourceGalleryProxyAsync(System.Guid guid) {
            this.ResourceGalleryProxyAsync(guid, null);
        }
        
        /// <remarks/>
        public void ResourceGalleryProxyAsync(System.Guid guid, object userState) {
            if ((this.ResourceGalleryProxyOperationCompleted == null)) {
                this.ResourceGalleryProxyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResourceGalleryProxyOperationCompleted);
            }
            this.InvokeAsync("ResourceGalleryProxy", new object[] {
                        guid}, this.ResourceGalleryProxyOperationCompleted, userState);
        }
        
        private void OnResourceGalleryProxyOperationCompleted(object arg) {
            if ((this.ResourceGalleryProxyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResourceGalleryProxyCompleted(this, new ResourceGalleryProxyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices")]
    public partial class CmsResourceGallery {
        
        private System.Guid guidField;
        
        private string nameField;
        
        private string pathField;
        
        private CmsResourceGallery[] galleriesField;
        
        private CmsResource[] resourcesField;
        
        /// <remarks/>
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        public CmsResourceGallery[] Galleries {
            get {
                return this.galleriesField;
            }
            set {
                this.galleriesField = value;
            }
        }
        
        /// <remarks/>
        public CmsResource[] Resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eastsussex.gov.uk/Escc.Cms.WebServices")]
    public partial class CmsResource {
        
        private System.Guid guidField;
        
        private string nameField;
        
        private string displayNameField;
        
        private string pathField;
        
        /// <remarks/>
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RootResourceGalleryProxyCompletedEventHandler(object sender, RootResourceGalleryProxyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RootResourceGalleryProxyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RootResourceGalleryProxyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CmsResourceGallery Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CmsResourceGallery)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ResourceGalleryProxyCompletedEventHandler(object sender, ResourceGalleryProxyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResourceGalleryProxyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResourceGalleryProxyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CmsResourceGallery Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CmsResourceGallery)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591